# Generated by Django 4.2.11 on 2025-02-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafintech_api', '0003_delete_hsn'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSN',
            fields=[
                ('cid', models.CharField(max_length=2)),
                ('hsnCode', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('hsnShortDescription', models.CharField(max_length=50)),
                ('hsnDescription', models.CharField(max_length=500)),
                ('isService', models.CharField(max_length=1)),
                ('gstTaxRate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': '[sales].[HSN]',
                'managed': False,
            },
        ),
    ]
